name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

### not using cla assistant, just adding this so that it passes
jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
                - uses: actions/setup-node@v1
                with:
                  node-version: "12.x"
                  - name: Install dependencies
                    run: yarn